

services:
  frontend:
    build: ./dashboard
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - finance-network

  fulldashboard:
    build:
      context: ./fulldashboard
      dockerfile: Dockerfile
    ports:
      - "81:80"
    depends_on:
      - backend
    networks:
      - finance-network

  backend:
    build: ./backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=finance;Username=financeuser;Password=financepass
      - Jwt__Key=your_jwt_key_here
      - Jwt__Issuer=http://localhost:5001
      - Jwt__Audience=http://localhost:5001
    ports:
      - "5001:5001"
    depends_on:
      - db
    networks:
      - finance-network

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: finance
      POSTGRES_USER: financeuser
      POSTGRES_PASSWORD: financepass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - finance-network

volumes:
  pgdata:

networks:
  finance-network:
    driver: bridge
