services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: financeapp
      POSTGRES_USER: financeuser
      POSTGRES_PASSWORD: financepass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5001
      
      ConnectionStrings__DefaultConnection: Host=db;Database=financeapp;Username=financeuser;Password=financepass
      
      POSTGRES_DB: financeapp
      POSTGRES_USER: financeuser
      POSTGRES_PASSWORD: financepass
      
      Logging__LogLevel__Default: Information
      Logging__LogLevel__Microsoft.AspNetCore: Warning
      
      Jwt__Key: SuperSecretKey123SuperSecretKey123SuperSecretKey123
      Jwt__Issuer: http://localhost:5001
      Jwt__Audience: http://localhost:8080
      Jwt__ExpiresInMinutes: 60
      
      AllowedHosts: "*"
    ports:
      - "5001:5001"

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - backend

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:5001
    depends_on:
      - backend

volumes:
  pgdata:
